In [7]:
import pandas as pd

In [8]:
car=pd.read_csv("C:/Users/91944/Desktop/car_data.csv")

In [9]:
car.head(1)

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0

In [10]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [11]:
print(car['Seller_Type'].unique())
print(car['Fuel_Type'].unique())
print(car['Transmission'].unique())
print(car['Owner'].unique())


['Dealer' 'Individual']
['Petrol' 'Diesel' 'CNG']
['Manual' 'Automatic']
[0 1 3]


In [12]:
car.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [13]:
# Going to create nwe dataset 

In [14]:
car_dataset=car[['Year','Selling_Price','Present_Price','Kms_Driven','Fuel_Type','Seller_Type','Transmission','Owner']]

In [15]:
car_dataset['Current_year']=2020

In [16]:
car_dataset.head(3)

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   

  Transmission  Owner  Current_year  
0       Manual      0          2020  
1       Manual      0          2020  
2       Manual      0          2020

In [17]:
# how many years you have used this car 

# so the code means car_dataset 0f current year (-) sub with car_dataset of year

In [18]:
car_dataset['Used_Years']=car_dataset['Current_year']-car_dataset['Year']

In [19]:
car_dataset.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   
2  2017           7.25           9.85        6900    Petrol      Dealer   
3  2011           2.85           4.15        5200    Petrol      Dealer   
4  2014           4.60           6.87       42450    Diesel      Dealer   

  Transmission  Owner  Current_year  Used_Years  
0       Manual      0          2020           6  
1       Manual      0          2020           7  
2       Manual      0          2020           3  
3       Manual      0          2020           9  
4       Manual      0          2020           6

In [20]:
# Here we are going to drop Years fron the dataset

In [21]:
car_dataset.drop(['Year'],axis=1,inplace=True)

In [22]:
car_dataset.head(3)

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   
2           7.25           9.85        6900    Petrol      Dealer   

  Transmission  Owner  Current_year  Used_Years  
0       Manual      0          2020           6  
1       Manual      0          2020           7  
2       Manual      0          2020           3

In [23]:
#Get dummies of this data set 

In [24]:
car_dataset=pd.get_dummies(car_dataset,drop_first=True)

In [25]:
car_dataset.head(1)

Selling_Price  Present_Price  Kms_Driven  Owner  Current_year  Used_Years  \
0           3.35           5.59       27000      0          2020           6   

   Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Individual  \
0                 0                 1                       0   

   Transmission_Manual  
0                    1

In [26]:
# from this data set i am going to drop the year 

In [27]:
car_dataset=car_dataset.drop(['Current_year'],axis=1)

In [67]:
car_dataset.head(1)

Selling_Price  Present_Price  Kms_Driven  Owner  Used_Years  \
0           3.35           5.59       27000      0           6   

   Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Individual  \
0                 0                 1                       0   

   Transmission_Manual  
0                    1

In [68]:
# Now we are going to train test splt the dataset 

In [28]:
x=car_dataset.iloc[:,1:]
y=car_dataset.iloc[: ,0]
 

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [ ]:
#Here you can see how many car the owner have 

In [70]:
x['Owner'].unique()

array([0, 1, 3], dtype=int64)

In [72]:
# now we are going to extract the regressor

In [81]:
from sklearn.ensemble import ExtraTreesRegressor
model=ExtraTreesRegressor()
import matplotlib.pyplot as plt
model.fit(x,y)

ExtraTreesRegressor()

In [75]:
#train test split

In [77]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [83]:
# we are going to get the random forest regressor 

In [105]:
from sklearn.ensemble import RandomForestRegressor

In [85]:
# Where ever we are calling RandomForestRegressor we have to call regressor

In [86]:
regressor= RandomForestRegressor()

In [88]:
import numpy as np

In [89]:
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
print(n_estimators)

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]


In [106]:
from sklearn.model_selection import RandomizedSearchCV

In [100]:
 #Randomized Search CV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]


In [92]:
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}


In [93]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()

In [94]:
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,scoring='neg_mean_squared_error', n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

In [96]:
rf_random.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.7s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   0.9s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   0.9s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimator

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [102]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 25}

In [103]:
rf_random.best_score_

-4.10886600908953

In [109]:
predictions=rf_random.predict(x_test)

In [110]:
predictions

array([10.71913,  0.60591,  4.16902,  3.69405,  7.84982,  4.8484 ,
        3.54915,  7.64733,  0.38518,  5.7011 ,  6.71049,  4.71045,
        0.78564,  8.54938,  2.59643,  0.67613,  0.75469,  1.04755,
        9.79036,  4.2169 ,  1.08437,  8.1421 ,  0.54738,  7.54825,
        0.5817 ,  7.67935,  0.64138,  0.29872,  3.4973 ,  2.72417,
        0.72059,  3.69757,  6.15223,  8.81179,  0.36527,  5.35017,
        8.92815,  6.01117,  6.34784,  5.80846, 13.45004,  0.90011,
        0.51114,  0.48409,  9.00571,  6.69583,  0.45084,  5.33303,
       11.69868,  3.19532,  7.6818 ,  0.45236,  6.80955,  0.6228 ,
        0.86522,  0.45786,  0.47704,  5.45556,  0.52425,  0.24266,
        8.93839,  6.69244,  1.40599,  3.9001 ,  0.51039,  3.9904 ,
        3.09422,  1.1125 ,  0.65614,  0.66465,  0.63035,  4.1896 ,
        7.00523,  0.48696,  2.24204,  4.76739,  0.71986,  1.39346,
        6.51637,  4.66992,  4.56505, 11.82256,  3.19138,  5.09985,
        0.9399 ,  0.56286,  3.61116,  2.13701,  4.66157,  0.99

In [117]:
from sklearn import metrics

In [118]:
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

MAE: 0.7943597802197822
MSE: 2.595795765487927
RMSE: 1.6111473444374749


In [112]:
#this library will help us to dump up all the datas 

In [113]:
import pickle

In [128]:
file=open('random_forest_regression_model11.pkl','wb')

In [129]:
pwd

'C:\\Users\\91944'

In [127]:
pickle.dump(rf_random,file)